<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<title>Try</title>
</head>

<body>

<?php
$name = $_POST['name'];
$email = $_POST['email'];
$company = $_POST['company'];
$agree = $_POST['c1'];

if($agree == '') {
	echo '<meta http-equiv="refresh" content="0; url=../login.php?try=n&name=' . $name . '&email=' . $email . '&company=' . $company . '">';

}
else {

// multiple recipients
$to  = 'emil@realfiction.com' . ', '; // note the comma
$to  = 'support@realfiction.com' . ', ';
$to .= 'eva@realfiction.com';

// subject
$subject = 'New user wants to try DreamocCMS';

// message
$message = '
<html>
<head>
  <title>New user wants to try DreamocCMS</title>
</head>
<body>
  <p>New user wants to try DreamocCMS</p>
  <table>
    <tr>
      <th>Name</th><th>e-mail</th><th>company</th>
    </tr>
    <tr>
      <td>' . $name . '</td><td>' . $email . '</td><td>' . $company . '</td>
    </tr>
  </table>
  <br>
  DreamocCMS autogenerated mail from cms.dreamoc.com
</body>
</html>
';

// To send HTML mail, the Content-type header must be set
$headers  = 'MIME-Version: 1.0' . "\r\n";
$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";

// Additional headers
//$headers .= 'To: Mary <mary@example.com>, Kelly <kelly@example.com>' . "\r\n";
$headers .= 'From: DreamocCMS <cms@dreamoc.com>' . "\r\n";
//$headers .= 'Cc: birthdayarchive@example.com' . "\r\n";
//$headers .= 'Bcc: birthdaycheck@example.com' . "\r\n";

// Mail it
//mail($to, $subject, $message, $headers);

//echo $message;

//header('Location: ../../login.php?try=y');
echo '<meta http-equiv="refresh" content="0; url=../login.php?try=y">';
}
?>

</body>
</html>